/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.CrearCheques;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan
 */
public class MantChk extends javax.swing.JFrame {
public static String Orden;
    /**
     * Creates new form MantChk
     */
    public MantChk() {
        initComponents();
        DefaultTableModel tabla= (DefaultTableModel) MantChk.jTable1.getModel();
        MantChk.jDateChooserFecha1.setDateFormatString("dd/MM/yyyy");
        MantChk.jDateChooserFecha2.setDateFormatString("dd/MM/yyyy");
        Date date = new Date(); 
        MantChk.jDateChooserFecha1.setDate(date); 
        MantChk.jDateChooserFecha2.setDate(date); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateChooserFecha1 = new com.toedter.calendar.JDateChooser();
        jDateChooserFecha2 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        todos = new javax.swing.JRadioButton();
        conciliado = new javax.swing.JRadioButton();
        impreso = new javax.swing.JRadioButton();
        anulado = new javax.swing.JRadioButton();
        trancito = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmdcancelar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Estado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Tipo = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        cuenta = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(910, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);
        jPanel1.add(jDateChooserFecha1);
        jDateChooserFecha1.setBounds(700, 20, 152, 32);
        jPanel1.add(jDateChooserFecha2);
        jDateChooserFecha2.setBounds(700, 70, 152, 32);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        todos.setBackground(new java.awt.Color(204, 255, 255));
        todos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        todos.setSelected(true);
        todos.setText("Todos");
        todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosActionPerformed(evt);
            }
        });

        conciliado.setBackground(new java.awt.Color(204, 255, 255));
        conciliado.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        conciliado.setText("Conciliado");
        conciliado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conciliadoActionPerformed(evt);
            }
        });

        impreso.setBackground(new java.awt.Color(204, 255, 255));
        impreso.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        impreso.setText("Impresos");
        impreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                impresoActionPerformed(evt);
            }
        });

        anulado.setBackground(new java.awt.Color(204, 255, 255));
        anulado.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        anulado.setText("Anulado");
        anulado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anuladoActionPerformed(evt);
            }
        });

        trancito.setBackground(new java.awt.Color(204, 255, 255));
        trancito.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        trancito.setText("Transito");
        trancito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trancitoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(todos)
                .addGap(10, 10, 10)
                .addComponent(impreso)
                .addGap(18, 18, 18)
                .addComponent(anulado)
                .addGap(18, 18, 18)
                .addComponent(trancito)
                .addGap(10, 10, 10)
                .addComponent(conciliado)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(todos)
                    .addComponent(impreso)
                    .addComponent(anulado)
                    .addComponent(trancito)
                    .addComponent(conciliado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(130, 10, 430, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Zoom-icon.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 10, 110, 49);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Fecha", "Tipo", "Beneficiario", "Detalle", "Monto", "Estado", "Actualizar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(50);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(1).setMinWidth(75);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(75);
            jTable1.getColumnModel().getColumn(2).setMinWidth(75);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(75);
            jTable1.getColumnModel().getColumn(3).setMinWidth(200);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(4).setMinWidth(200);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(5).setMinWidth(75);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(75);
            jTable1.getColumnModel().getColumn(6).setMinWidth(75);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(75);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(12, 132, 840, 412);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Cuenta Bancaria:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 80, 103, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("x Fecha del:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(610, 30, 71, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Al");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(670, 80, 12, 15);

        cmdcancelar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cmdcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Apps-Dialog-Logout-icon.png"))); // NOI18N
        cmdcancelar.setText("Cancelar");
        cmdcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdcancelar);
        cmdcancelar.setBounds(720, 550, 140, 47);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Apps-system-software-update-icon.png"))); // NOI18N
        jButton3.setText("ACTUALIZAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(160, 550, 137, 50);

        Estado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Estado.setForeground(new java.awt.Color(0, 0, 255));
        Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Impreso", "Anulado", "Transito", "Conciliado" }));
        jPanel1.add(Estado);
        Estado.setBounds(360, 550, 115, 47);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("ESTADO:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 550, 53, 47);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("TIPO:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(480, 570, 33, 15);

        Tipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Tipo.setForeground(new java.awt.Color(0, 0, 255));
        Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Venta", "Gasto", "Deposito" }));
        jPanel1.add(Tipo);
        Tipo.setBounds(530, 550, 115, 47);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Actions-trash-empty-icon.png"))); // NOI18N
        jButton2.setText("ELIMINAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 550, 130, 50);

        cuenta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cuenta.setToolTipText("");
        jPanel1.add(cuenta);
        cuenta.setBounds(130, 70, 250, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 60, 870, 610);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("M A N T E N I M I E N T O    D E    C H E Q U E S    G I R A D O S");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel5)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 10, 870, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_cmdcancelarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int contador=0;

        for (int i = 0; i < MantChk.jTable1.getRowCount(); i++) {

            if( MantChk.jTable1.isCellSelected(i, 6)){
                contador = contador + 1;
            }else{
                continue;
            }
        }
        if (contador!=0){
            if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente eliminar el registro?", "Eliminar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                CrearCheques crear = new CrearCheques();
                crear.eliminarcheque();
                crear.cargarcheques();
            }
        }else{
            JOptionPane.showMessageDialog(null, "NO HAY UN REGISTRO SELECCIONADO PARA ELIMINAR", "Eliminacion", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                CrearCheques carga = new CrearCheques();
        Orden = "1";
        carga.llenarcombo();
        carga.cargarcheques();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              CrearCheques carga1 = new CrearCheques();
        carga1.cargarcheques();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                   int contador=0;
      
      for (int i = 0; i < MantChk.jTable1.getRowCount(); i++) {

            if( MantChk.jTable1.isCellSelected(i, 6)){ 
                contador = contador + 1;  
            }else{
                continue;
            }
      }   
        if (contador!=0){
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente actualizar el registro?", "Eliminar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            CrearCheques actualiza = new CrearCheques();
            actualiza.ActualizarCheques();
            actualiza.cargarcheques();
        }     
         }else{
            JOptionPane.showMessageDialog(null, "NO HAY REGISTRO SELECCIONADO PARA ACTUALIZAR", "Actualizacion", JOptionPane.WARNING_MESSAGE); 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosActionPerformed
        MantChk.todos.setSelected(true);
        MantChk.impreso.setSelected(false);
        MantChk.trancito.setSelected(false);
        MantChk.anulado.setSelected(false);
        MantChk.conciliado.setSelected(false);  
    }//GEN-LAST:event_todosActionPerformed

    private void impresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impresoActionPerformed
        MantChk.todos.setSelected(false);
        MantChk.impreso.setSelected(true);
        MantChk.trancito.setSelected(false);
        MantChk.anulado.setSelected(false);
        MantChk.conciliado.setSelected(false);  
    }//GEN-LAST:event_impresoActionPerformed

    private void anuladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anuladoActionPerformed
        MantChk.todos.setSelected(false);
        MantChk.impreso.setSelected(false);
        MantChk.trancito.setSelected(false);
        MantChk.anulado.setSelected(true);
        MantChk.conciliado.setSelected(false);  
    }//GEN-LAST:event_anuladoActionPerformed

    private void trancitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trancitoActionPerformed
        MantChk.todos.setSelected(false);
        MantChk.impreso.setSelected(false);
        MantChk.trancito.setSelected(true);
        MantChk.anulado.setSelected(false);
        MantChk.conciliado.setSelected(false);  
    }//GEN-LAST:event_trancitoActionPerformed

    private void conciliadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conciliadoActionPerformed
        MantChk.todos.setSelected(false);
        MantChk.impreso.setSelected(false);
        MantChk.trancito.setSelected(false);
        MantChk.anulado.setSelected(false);
        MantChk.conciliado.setSelected(true);  
    }//GEN-LAST:event_conciliadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantChk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantChk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantChk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantChk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantChk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> Estado;
    public static javax.swing.JComboBox<String> Tipo;
    public static javax.swing.JRadioButton anulado;
    private javax.swing.JButton cmdcancelar;
    public static javax.swing.JRadioButton conciliado;
    public static javax.swing.JComboBox<String> cuenta;
    public static javax.swing.JRadioButton impreso;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public static com.toedter.calendar.JDateChooser jDateChooserFecha1;
    public static com.toedter.calendar.JDateChooser jDateChooserFecha2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JRadioButton todos;
    public static javax.swing.JRadioButton trancito;
    // End of variables declaration//GEN-END:variables
}
