/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.CrearProvedor;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class Proveedor extends javax.swing.JFrame {

    /**
     * Creates new form Proveedor
     */
    public Proveedor() {
        initComponents();
        Proveedor.fecha.setDateFormatString("dd/MM/yyyy");
        Date date = new Date(); 
        Proveedor.fecha.setDate(date); 
        CrearProvedor ch = new CrearProvedor();        
        this.codigo.setText(ch.buscarultimo().toString());
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        codigo = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        dv = new javax.swing.JTextField();
        tel01 = new javax.swing.JTextField();
        ruc = new javax.swing.JTextField();
        tel02 = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        estado = new javax.swing.JComboBox<>();
        fecha = new com.toedter.calendar.JDateChooser();
        lbl_foto = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nuevo = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        listar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        codigo.setEditable(false);
        codigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });
        codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoKeyTyped(evt);
            }
        });
        jPanel2.add(codigo);
        codigo.setBounds(110, 20, 209, 30);

        nombre.setEditable(false);
        nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel2.add(nombre);
        nombre.setBounds(110, 60, 209, 30);

        dv.setEditable(false);
        dv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dvActionPerformed(evt);
            }
        });
        jPanel2.add(dv);
        dv.setBounds(110, 100, 209, 30);

        tel01.setEditable(false);
        tel01.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tel01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tel01ActionPerformed(evt);
            }
        });
        jPanel2.add(tel01);
        tel01.setBounds(110, 180, 209, 30);

        ruc.setEditable(false);
        ruc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ruc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rucActionPerformed(evt);
            }
        });
        jPanel2.add(ruc);
        ruc.setBounds(110, 140, 209, 30);

        tel02.setEditable(false);
        tel02.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tel02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tel02ActionPerformed(evt);
            }
        });
        jPanel2.add(tel02);
        tel02.setBounds(111, 216, 209, 30);

        direccion.setEditable(false);
        direccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });
        jPanel2.add(direccion);
        direccion.setBounds(110, 260, 347, 115);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("*ID PROVEEDOR:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 30, 89, 13);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("*NOMBRE:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 70, 53, 13);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("D.V.");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 110, 21, 13);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("*DIRECCION:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 280, 69, 13);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("TELEFONO 2:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(12, 221, 67, 13);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("E-MAIL:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(490, 80, 41, 13);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("ESTADO:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(490, 110, 70, 58);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("FECHA");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(490, 30, 35, 28);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setText("*R.U.C.:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 150, 39, 13);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setText("*TELEFONO 1:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 190, 73, 13);

        estado.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));
        jPanel2.add(estado);
        estado.setBounds(560, 120, 150, 30);
        jPanel2.add(fecha);
        fecha.setBounds(560, 30, 150, 28);

        lbl_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/proveedores.png"))); // NOI18N
        lbl_foto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(lbl_foto);
        lbl_foto.setBounds(500, 170, 248, 200);

        email.setEditable(false);
        jPanel2.add(email);
        email.setBounds(560, 70, 150, 30);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("R E G I S T R O   Y   C O N S U L T A   D E  P R O V E E D O R E S   D E L   S I S T E M A ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nuevo.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Actions-list-add-user-icon.png"))); // NOI18N
        nuevo.setText("NUEVO");
        nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        editar.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Developmer Folder.png"))); // NOI18N
        editar.setText("EDITAR");
        editar.setEnabled(false);
        editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        eliminar.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Misc-Delete-Database-icon.png"))); // NOI18N
        eliminar.setText("ELIMINAR");
        eliminar.setEnabled(false);
        eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        listar.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Distributor-report-icon.png"))); // NOI18N
        listar.setText("LISTAR");
        listar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarActionPerformed(evt);
            }
        });

        guardar.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Save-icon.png"))); // NOI18N
        guardar.setText("GUARDAR");
        guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        salir.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Perspective-Button-Shutdown-icon.png"))); // NOI18N
        salir.setText("SALIR");
        salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
        evt.setSource((char) KeyEvent.VK_ENTER);
        nombre.requestFocus();
    }//GEN-LAST:event_codigoActionPerformed

    private void codigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoKeyReleased

    private void codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            evt.consume();
        }
    }//GEN-LAST:event_codigoKeyTyped

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
        evt.setSource((char) KeyEvent.VK_ENTER);
        dv.requestFocus();
    }//GEN-LAST:event_nombreActionPerformed

    private void dvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dvActionPerformed
        // TODO add your handling code here:
        evt.setSource((char) KeyEvent.VK_ENTER);
        ruc.requestFocus();
    }//GEN-LAST:event_dvActionPerformed

    private void tel01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tel01ActionPerformed
        // TODO add your handling code here:
        evt.setSource((char) KeyEvent.VK_ENTER);
        tel02.requestFocus();
    }//GEN-LAST:event_tel01ActionPerformed

    private void rucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rucActionPerformed
        // TODO add your handling code here:
        evt.setSource((char) KeyEvent.VK_ENTER);
        tel01.requestFocus();
    }//GEN-LAST:event_rucActionPerformed

    private void tel02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tel02ActionPerformed
        // TODO add your handling code here:
        evt.setSource((char) KeyEvent.VK_ENTER);
        direccion.requestFocus();
    }//GEN-LAST:event_tel02ActionPerformed

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
        // TODO add your handling code here:
        evt.setSource((char) KeyEvent.VK_ENTER);
        fecha.requestFocus();
    }//GEN-LAST:event_direccionActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed

        Habilitar();
    }//GEN-LAST:event_nuevoActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
      String idproveedor,nombre,Dv,Direccion,Ruc, Telefono01, Telefono02, Email, estado, Fecha;
      Integer codigox;
      try {
         if ((this.codigo.getText().trim().length()==0) || (this.nombre.getText().trim().length()==0) || (this.direccion.getText().trim().length()==0)|| (this.tel01.getText().trim().length()==0)|| (this.email.getText().trim().length()==0)  ) {
         JOptionPane.showMessageDialog(null, "Los Campos Con Aterisco No pueden Estar En Blanco");
         }else{    
            CrearProvedor cliente = new CrearProvedor();
            codigox= Integer.parseInt(codigo.getText());
            nombre=Proveedor.nombre.getText();
            Dv=Proveedor.dv.getText();
            Direccion= Proveedor.direccion.getText();
            estado=Proveedor.estado.getSelectedItem().toString();
            Email=Proveedor.email.getText();
            Ruc=Proveedor.ruc.getText();
            Telefono01=Proveedor.tel01.getText();
            Telefono02=Proveedor.tel02.getText();
            //-----obtener la fecha----------------------
      String  dia = Integer.toString(fecha.getCalendar().get(Calendar.DAY_OF_MONTH));
      String  mes = Integer.toString(fecha.getCalendar().get(Calendar.MONTH) + 1);
      String year = Integer.toString(fecha.getCalendar().get(Calendar.YEAR));
     // Fecha1 = (year + "-" + mes+ "-" + dia);    
      Fecha = (year + "-" + mes+ "-" + dia);
     //---------fin de obtener la fecha
           // Fecha1=jDateChooserFecha1.getDate().toString();
            //Fecha2=jDateChooserFecha1.getDate().toString();
            cliente.editarproveedor(codigox, nombre, Dv, Ruc, Direccion, Telefono01, Telefono02, Email, estado, Fecha);
       // crear.guardar(idClientes, Nombre, Apellido, Cedula, Direccion, Telefono1, Telefono2, Credito, Imagen, Estado, Audito1, Audito2, Fecha1, Fecha2);   
      // JOptionPane.showMessageDialog(null,"REGISTRO EDITADO CORRECTAMENTE " );
         }
        }catch(Exception ex) {
       JOptionPane.showMessageDialog(null,"Error  = " +ex);
       }
    }//GEN-LAST:event_editarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        Integer Codigo =  Integer.parseInt(this.codigo.getText());
        CrearProvedor crear = new CrearProvedor();
        crear.eliminarproveedor(Codigo);
    }//GEN-LAST:event_eliminarActionPerformed

    private void listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarActionPerformed
        try{
           BuscarProveedor list = new BuscarProveedor();
            list.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error:"+ex);
        }

    }//GEN-LAST:event_listarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        CrearProvedor user = new CrearProvedor();
        user.guardarproveedor();
        Limpiar();
        Habilitar();  
        CrearProvedor ch = new CrearProvedor();        
        this.codigo.setText(ch.buscarultimo().toString());
    }//GEN-LAST:event_guardarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField codigo;
    public static javax.swing.JTextField direccion;
    public static javax.swing.JTextField dv;
    public static javax.swing.JButton editar;
    public static javax.swing.JButton eliminar;
    public static javax.swing.JTextField email;
    public static javax.swing.JComboBox<String> estado;
    public static com.toedter.calendar.JDateChooser fecha;
    public static javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_foto;
    private javax.swing.JButton listar;
    public static javax.swing.JTextField nombre;
    private javax.swing.JButton nuevo;
    public static javax.swing.JTextField ruc;
    private javax.swing.JButton salir;
    public static javax.swing.JTextField tel01;
    public static javax.swing.JTextField tel02;
    // End of variables declaration//GEN-END:variables

  public void Limpiar(){
    
        Proveedor.codigo.setText("");
        Proveedor.nombre.setText("");
        Proveedor.dv.setText("");
        Proveedor.ruc.setText("");
        Proveedor.tel01.setText("");
        Proveedor.tel02.setText("");
        Proveedor.direccion.setText("");
        Proveedor.email.setText("");
        
}

public void Habilitar(){
    
        Proveedor.nombre.setEditable(true);
        Proveedor.dv.setEditable(true);
        Proveedor.ruc.setEditable(true);
        Proveedor.tel01.setEditable(true);
        Proveedor.tel02.setEditable(true);
        Proveedor.direccion.setEditable(true);
        Proveedor.email.setEditable(true);
}
}
