/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.conectar;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import Clases.subastas;
import Clases.redondear;
import Clases.lotes;
import static Interfaces.Clientes.jDateChooserFecha1;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Random;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.JRPrintServiceExporter;
import net.sf.jasperreports.engine.export.JRPrintServiceExporterParameter;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Juan
 */
public class Subastas extends javax.swing.JFrame {
     Integer cod,codigo,cant;
   public static String fecha;
     String fer2="", fer3="", fer4="",fer5="",fer6="",fer7="";
   public static Integer idaimal;
   public static List<String> Lista = new ArrayList<String>();
     
       /**
     * Creates new form Subastas
     */
    public Subastas() {
        initComponents();
        this.jDateChooserFecha.setDateFormatString("dd/MM/yyyy");
        Date date = new Date(); 
        this.jDateChooserFecha.setDate(date); 
        //-----obtener la fecha----------------------
      String  dia = Integer.toString(jDateChooserFecha.getCalendar().get(Calendar.DAY_OF_MONTH));
      String  mes = Integer.toString(jDateChooserFecha.getCalendar().get(Calendar.MONTH) + 1);
      String year = Integer.toString(jDateChooserFecha.getCalendar().get(Calendar.YEAR));
      fecha = (year + "-" + mes+ "-" + dia);    
     //---------fin de obtener la fecha 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupLotes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldNombredelcomprador = new javax.swing.JTextField();
        jTextFieldPesoNeto = new javax.swing.JTextField();
        jTextFieldCeduladelcomprador = new javax.swing.JTextField();
        jTextFieldCheques = new javax.swing.JTextField();
        jTextFieldPorsubastar = new javax.swing.JTextField();
        jTextFieldHembras = new javax.swing.JTextField();
        jTextFieldTotaldeanimales = new javax.swing.JTextField();
        jTextFieldMachos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSubastados = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonListaIndividual = new javax.swing.JButton();
        jButtonNosubastado = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonIndividual = new javax.swing.JRadioButton();
        jRadioButtonPorlote = new javax.swing.JRadioButton();
        jTextFieldNumerodelote = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNanimal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCodigoComprador = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldColor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldTipo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldFerrete = new javax.swing.JTextField();
        jTextFieldSexo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        jTextFieldDetalle = new javax.swing.JTextField();
        jButtonVerLote = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelPrecioPactado = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldPrecioPactado = new javax.swing.JTextField();
        jTextFieldMontoTotal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButtonLista = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(909, 650));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("SUBASTAS     DE     ANIMALES     POR     PRECIO     PACTADO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel1)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jTextFieldNombredelcomprador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNombredelcomprador.setEnabled(false);
        jPanel2.add(jTextFieldNombredelcomprador);
        jTextFieldNombredelcomprador.setBounds(160, 280, 250, 30);

        jTextFieldPesoNeto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPesoNeto.setEnabled(false);
        jPanel2.add(jTextFieldPesoNeto);
        jTextFieldPesoNeto.setBounds(100, 340, 70, 30);

        jTextFieldCeduladelcomprador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCeduladelcomprador.setEnabled(false);
        jPanel2.add(jTextFieldCeduladelcomprador);
        jTextFieldCeduladelcomprador.setBounds(500, 280, 130, 30);

        jTextFieldCheques.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldCheques.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldCheques.setForeground(new java.awt.Color(0, 255, 0));
        jTextFieldCheques.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCheques.setText("0");
        jPanel2.add(jTextFieldCheques);
        jTextFieldCheques.setBounds(620, 530, 120, 30);

        jTextFieldPorsubastar.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldPorsubastar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPorsubastar.setForeground(new java.awt.Color(0, 255, 0));
        jTextFieldPorsubastar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPorsubastar.setText("0");
        jPanel2.add(jTextFieldPorsubastar);
        jTextFieldPorsubastar.setBounds(470, 530, 100, 30);

        jTextFieldHembras.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldHembras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldHembras.setForeground(new java.awt.Color(0, 255, 0));
        jTextFieldHembras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldHembras.setText("0");
        jPanel2.add(jTextFieldHembras);
        jTextFieldHembras.setBounds(320, 530, 90, 30);

        jTextFieldTotaldeanimales.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldTotaldeanimales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldTotaldeanimales.setForeground(new java.awt.Color(0, 255, 0));
        jTextFieldTotaldeanimales.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTotaldeanimales.setText("0");
        jPanel2.add(jTextFieldTotaldeanimales);
        jTextFieldTotaldeanimales.setBounds(20, 530, 100, 30);

        jTextFieldMachos.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldMachos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldMachos.setForeground(new java.awt.Color(0, 255, 0));
        jTextFieldMachos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMachos.setText("0");
        jPanel2.add(jTextFieldMachos);
        jTextFieldMachos.setBounds(180, 530, 90, 30);

        jTableSubastados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "# llegada", "Descripcion", "Sexo", "Color", "Precio Unit.", "Peso", "Cod. Comprador"
            }
        ));
        jScrollPane1.setViewportView(jTableSubastados);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 390, 720, 120);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Product-sale-report-icon.png"))); // NOI18N
        jButton2.setText("COMPRADORES");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(760, 270, 110, 60);

        jButtonGuardar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Save-icon.png"))); // NOI18N
        jButtonGuardar.setText("GRABAR");
        jButtonGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jButtonGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonGuardarKeyPressed(evt);
            }
        });
        jPanel2.add(jButtonGuardar);
        jButtonGuardar.setBounds(760, 440, 112, 60);

        jButtonListaIndividual.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButtonListaIndividual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Distributor-report-icon.png"))); // NOI18N
        jButtonListaIndividual.setText("VENDEDORES");
        jButtonListaIndividual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonListaIndividual.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonListaIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaIndividualActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonListaIndividual);
        jButtonListaIndividual.setBounds(760, 330, 110, 60);

        jButtonNosubastado.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonNosubastado.setForeground(new java.awt.Color(0, 0, 255));
        jButtonNosubastado.setText("GANADO NO SUBASTADO");
        jButtonNosubastado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNosubastadoActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNosubastado);
        jButtonNosubastado.setBounds(570, 325, 170, 50);

        btn_salir.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Perspective-Button-Shutdown-icon.png"))); // NOI18N
        btn_salir.setText("SALIR");
        btn_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel2.add(btn_salir);
        btn_salir.setBounds(760, 500, 112, 60);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("FECHA:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("TIPO SUBASTA:");

        jRadioButtonIndividual.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupLotes.add(jRadioButtonIndividual);
        jRadioButtonIndividual.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jRadioButtonIndividual.setSelected(true);
        jRadioButtonIndividual.setText("INDUVIDUAL");
        jRadioButtonIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIndividualActionPerformed(evt);
            }
        });

        jRadioButtonPorlote.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupLotes.add(jRadioButtonPorlote);
        jRadioButtonPorlote.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jRadioButtonPorlote.setText("POR LOTE   -   No. LOTE");
        jRadioButtonPorlote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPorloteActionPerformed(evt);
            }
        });

        jTextFieldNumerodelote.setEnabled(false);
        jTextFieldNumerodelote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumerodeloteActionPerformed(evt);
            }
        });
        jTextFieldNumerodelote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNumerodeloteKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("No. ANIMAL:");

        jTextFieldNanimal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldNanimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNanimalActionPerformed(evt);
            }
        });
        jTextFieldNanimal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNanimalKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("PRECIO:");

        jTextFieldPrecio.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldPrecio.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextFieldPrecio.setForeground(new java.awt.Color(0, 255, 0));
        jTextFieldPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });
        jTextFieldPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("No. COMPRADOR");

        jTextFieldCodigoComprador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldCodigoComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoCompradorActionPerformed(evt);
            }
        });
        jTextFieldCodigoComprador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoCompradorKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("OBSERVACIONES:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("PESO:");

        jTextFieldPeso.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldPeso.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextFieldPeso.setForeground(new java.awt.Color(0, 255, 0));
        jTextFieldPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesoActionPerformed(evt);
            }
        });
        jTextFieldPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPesoKeyTyped(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Datos Del Animal");

        jTextFieldColor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldColor.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel15.setText("Tipo");

        jTextFieldTipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldTipo.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Color");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Sexo");

        jTextFieldFerrete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldFerrete.setEnabled(false);

        jTextFieldSexo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldSexo.setEnabled(false);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Ferrete");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldTipo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel12))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFerrete, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldFerrete, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(21, 21, 21))
        );

        jTextFieldDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDetalleActionPerformed(evt);
            }
        });

        jButtonVerLote.setText("Ver Lote");
        jButtonVerLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerLoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldDetalle))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCodigoComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(40, 40, 40)
                                .addComponent(jTextFieldNanimal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jTextFieldPrecio)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonIndividual)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonPorlote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNumerodelote, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonVerLote, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jRadioButtonIndividual)
                        .addComponent(jRadioButtonPorlote)
                        .addComponent(jTextFieldNumerodelote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonVerLote))
                    .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldNanimal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldCodigoComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(12, 13, 864, 240);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("NOMBRE COMPRADOR:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 290, 130, 13);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("CEDULA:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(440, 290, 45, 13);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("PESO NETO:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 350, 90, 15);

        jLabelPrecioPactado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPrecioPactado.setForeground(new java.awt.Color(255, 0, 0));
        jLabelPrecioPactado.setText("PRECIO PACTADO:");
        jPanel2.add(jLabelPrecioPactado);
        jLabelPrecioPactado.setBounds(170, 350, 160, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("MONTO TOTAL");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(370, 350, 87, 15);

        jTextFieldPrecioPactado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPrecioPactado.setEnabled(false);
        jPanel2.add(jTextFieldPrecioPactado);
        jTextFieldPrecioPactado.setBounds(290, 340, 70, 30);

        jTextFieldMontoTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldMontoTotal.setEnabled(false);
        jTextFieldMontoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMontoTotalActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldMontoTotal);
        jTextFieldMontoTotal.setBounds(460, 340, 100, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setText("MACHOS");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(180, 510, 90, 13);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 255));
        jLabel17.setText("HEMBRAS");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(320, 510, 90, 13);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 255));
        jLabel18.setText("CHEQUES");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(620, 510, 140, 13);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("TOTAL DE ANIMALES");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(20, 510, 111, 13);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 255));
        jLabel20.setText("POR SUBASTAR");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(470, 510, 110, 13);

        jButtonLista.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonLista.setText("LISTA");
        jButtonLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonLista);
        jButtonLista.setBounds(650, 280, 80, 30);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(20, 258, 850, 10);

        jButtonLimpiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Actions-list-add-icon.png"))); // NOI18N
        jButtonLimpiar.setText("NUEVO");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonLimpiar);
        jButtonLimpiar.setBounds(760, 390, 110, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_btn_salirActionPerformed

    private void jButtonListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaActionPerformed
        // TODO add your handling code here:
         try {
        buscarclientes list = new buscarclientes();
        list.setVisible(true); 
        buscarclientes.Validar="6";
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, "Error:"+ex);
        }
    }//GEN-LAST:event_jButtonListaActionPerformed

    private void jTextFieldCodigoCompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoCompradorActionPerformed
        // TODO add your handling code here:
        try{
      
       evt.setSource((char) KeyEvent.VK_ENTER);
       cod= Integer.parseInt(jTextFieldCodigoComprador.getText());     
       subastas sub = new subastas();
       sub.buscarcliente(cod);
      
      
        }catch (Exception ex){
        JOptionPane.showMessageDialog(null, "Error:"+ex);
        }
    }//GEN-LAST:event_jTextFieldCodigoCompradorActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        try{
           
           if (jRadioButtonIndividual.isSelected()==true){
           if ((jTextFieldNanimal.getText().trim().length()==0) || (jTextFieldCodigoComprador.getText().trim().length()==0)|| (jTextFieldTipo.getText().trim().length()==0) || (jTextFieldColor.getText().trim().length()==0)
                 || (jTextFieldSexo.getText().trim().length()==0) || (jTextFieldFerrete.getText().trim().length()==0) || (jTextFieldNombredelcomprador.getText().trim().length()==0)|| (jTextFieldCeduladelcomprador.getText().trim().length()==0)
                   || (jTextFieldPesoNeto.getText().trim().length()==0)|| (jTextFieldPrecioPactado.getText().trim().length()==0)|| (jTextFieldMontoTotal.getText().trim().length()==0)){
            JOptionPane.showMessageDialog(null,"Para Poder realizar Esta Operacion Debe Completar La Informacion En Las Cajas De Textos");
            jTextFieldNanimal.requestFocus();
           }else{
                        
           subastas suba = new subastas();
           suba.guardarsubasta();
           suba.machos();
           suba.hembras();
           suba.totalmachoshembras();
           suba.buscarporsubastar();
           suba.tablesubastado();
            }
               
           }
           
           if (this.jRadioButtonPorlote.isSelected()==true){
           if ((jTextFieldCodigoComprador.getText().trim().length()==0)|| (jTextFieldNombredelcomprador.getText().trim().length()==0)|| (jTextFieldCeduladelcomprador.getText().trim().length()==0)
              || (jTextFieldPesoNeto.getText().trim().length()==0)|| (jTextFieldPrecioPactado.getText().trim().length()==0)|| (jTextFieldMontoTotal.getText().trim().length()==0)){
            JOptionPane.showMessageDialog(null,"Para Poder realizar Esta Operacion Debe Completar La Informacion");
          
           }else{
           subastas suba = new subastas();
             //Iterator i = Lista.iterator();
        // while(i.hasNext())
        //{
            //idaimal= Integer.parseInt(i.next().toString());
            suba.guardarsubastaporlote();
        //}
        
           
           suba.machos();
           suba.hembras();
           suba.totalmachoshembras();
           suba.buscarporsubastar();
           suba.tablesubastado();
            }
               
           } 
           
        }catch(Exception ex){
       
        JOptionPane.showMessageDialog(null, "Error:"+ex);
        
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextFieldNanimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNanimalActionPerformed
        // TODO add your handling code here:
        try{
            /*
      //-----obtener la fecha----------------------
      String  dia = Integer.toString(jDateChooserFecha.getCalendar().get(Calendar.DAY_OF_MONTH));
      String  mes = Integer.toString(jDateChooserFecha.getCalendar().get(Calendar.MONTH) + 1);
      String year = Integer.toString(jDateChooserFecha.getCalendar().get(Calendar.YEAR));
      fecha = (year + "-" + mes+ "-" + dia);    
     //---------fin de obtener la fecha 
            */
       evt.setSource((char) KeyEvent.VK_ENTER);
       codigo= Integer.parseInt(jTextFieldNanimal.getText());     
       subastas sub = new subastas();
       sub.buscaranimal(codigo, fecha);
       
        }catch (Exception ex){
        JOptionPane.showMessageDialog(null, "Error:"+ex);
        }
    }//GEN-LAST:event_jTextFieldNanimalActionPerformed

    private void jTextFieldNanimalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNanimalKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
          if(Character.isLetter(c)){
              evt.consume();
          }
    }//GEN-LAST:event_jTextFieldNanimalKeyTyped

    private void jTextFieldCodigoCompradorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoCompradorKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
          if(Character.isLetter(c)){
              evt.consume();
          }
    }//GEN-LAST:event_jTextFieldCodigoCompradorKeyTyped

    private void jTextFieldPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
          if(Character.isLetter(c)){
              evt.consume();
          }
    }//GEN-LAST:event_jTextFieldPrecioKeyTyped

    private void jTextFieldPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
          if(Character.isLetter(c)){
              evt.consume();
          }
    }//GEN-LAST:event_jTextFieldPesoKeyTyped

    private void jTextFieldPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTextFieldPrecioKeyPressed

    private void jTextFieldPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioKeyReleased
        // TODO add your handling code here:
         jTextFieldPrecioPactado.setText(jTextFieldPrecio.getText());
    }//GEN-LAST:event_jTextFieldPrecioKeyReleased

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        // TODO add your handling code here:
        try{
       jTextFieldPeso.setText("0");
       jTextFieldPeso.selectAll();
       jTextFieldPeso.requestFocus();
       
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Error" +ex);        
        }
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        try{
        jTextFieldNanimal.requestFocus();
        subastas sub = new subastas();
       sub.machos();
       sub.hembras();
       sub.totalmachoshembras();
       sub.buscarporsubastar();
       sub.tablesubastado();
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Error" +ex); 
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
      try{
        Lista.clear();  
        jRadioButtonIndividual.setSelected(true);
        jTextFieldNumerodelote.setEnabled(false);
        jTextFieldNumerodelote.setText("");
        jTextFieldDetalle.setText("");
        jTextFieldNanimal.setText("");
        jTextFieldCodigoComprador.setText("");
        jTextFieldTipo.setText("");
        jTextFieldColor.setText("");
        jTextFieldSexo.setText("");
        jTextFieldFerrete.setText("");
        jTextFieldNombredelcomprador.setText("");
        jTextFieldCeduladelcomprador.setText("");
        jTextFieldPesoNeto.setText("");
        jTextFieldPrecioPactado.setText("");
        jTextFieldMontoTotal.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldPeso.setText("");
        jTextFieldNanimal.setEnabled(true);
        jTextFieldCodigoComprador.setEnabled(true);
        jTextFieldNanimal.requestFocus();
      }catch(Exception ex){
      JOptionPane.showMessageDialog(null,"Error" +ex); 
      }
        
        
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonNosubastadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNosubastadoActionPerformed
        // TODO add your handling code here:
        try{
        Nosubastados nsuba = new Nosubastados();
        nsuba.setVisible(true);
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Error" +ex); 
        }
        
    }//GEN-LAST:event_jButtonNosubastadoActionPerformed

    private void jButtonListaIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaIndividualActionPerformed
        // TODO add your handling code here:
      //  try{
     //   Reporteventaindividual rep = new Reporteventaindividual();
     //   rep.setVisible(true);
     //   }catch(Exception ex){
     //   JOptionPane.showMessageDialog(null,"Error" +ex);         
     //   }
     
     conectar conect = new conectar(); 
    conect.conexion();
  
       
            Calendar c1 = Calendar.getInstance();
      String  dia = Integer.toString(c1.get(Calendar.DAY_OF_MONTH));
      String  mes = Integer.toString(c1.get(Calendar.MONTH) + 1);
      String year = Integer.toString(c1.get(Calendar.YEAR));
      String Fecha = (year + "-" + mes+ "-" + dia);  
           
                      try {
                   
                    JasperReport jasperReport;
                    JasperPrint jasperPrint;
                
                     Map<String, Object> params = new HashMap<>();
                    String  ruta="C:\\SG-SOFT\\subastaganadera\\src\\ReportesSG\\" +  "vendedoresdia.jrxml";  
                    jasperReport =JasperCompileManager.compileReport(ruta);
                    params.put("Fecha", Fecha);

                    jasperPrint = JasperFillManager.fillReport(jasperReport, params, conect.con);
                  JasperViewer.viewReport(jasperPrint, false);


                 } catch (Exception ex) {
                    System.err.println("Error JRException: " + ex.getMessage());
                 }

      
    }//GEN-LAST:event_jButtonListaIndividualActionPerformed

    private void jTextFieldPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesoActionPerformed
        // TODO add your handling code here:
        try{
        double preciopactado,peso,montototal,total;   
        String montotal;
        //Double pesopromedio; 
        preciopactado= Double.parseDouble(jTextFieldPrecioPactado.getText());
        peso= Double.parseDouble(this.jTextFieldPesoNeto.getText());
        montototal=preciopactado * peso;
        redondear redon = new redondear();
        total=redon.redondearDecimales(montototal, 2);
        montotal=String.valueOf(total);
       this.jTextFieldMontoTotal.setText(montotal);
       jButtonGuardar.requestFocus();
       
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Error" +ex); 
        }
    }//GEN-LAST:event_jTextFieldPesoActionPerformed

    private void jTextFieldPesoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesoKeyReleased
        // TODO add your handling code here:
        try{
         Double pesopromedio,pesodellote,pesoindividual; 
          if(jTextFieldPeso.getText()==null){
          jTextFieldPeso.setText("0");
          jTextFieldPeso.selectAll();
          jTextFieldPeso.requestFocus();
          }else{
         if(jRadioButtonIndividual.isSelected()==true){   
         jTextFieldPesoNeto.setText(jTextFieldPeso.getText());
         }else{
         if (Lista.size()==1){
         JOptionPane.showMessageDialog(null,"El Proceso Que Desea Realizar No es Una Subasta Por Lote, Para Ello Deben Haber mas de Dos Animales"); 
         Lista.clear();
        jRadioButtonIndividual.setSelected(true);
        jTextFieldNumerodelote.setEnabled(false);
        jTextFieldNumerodelote.setText("");
        jTextFieldDetalle.setText("");
        jTextFieldNanimal.setText("");
        jTextFieldCodigoComprador.setText("");
        jTextFieldTipo.setText("");
        jTextFieldColor.setText("");
        jTextFieldSexo.setText("");
        jTextFieldFerrete.setText("");
        jTextFieldNombredelcomprador.setText("");
        jTextFieldCeduladelcomprador.setText("");
        jTextFieldPesoNeto.setText("");
        jTextFieldPrecioPactado.setText("");
        jTextFieldMontoTotal.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldPeso.setText("");
        jTextFieldNanimal.setEnabled(true);
        jTextFieldCodigoComprador.setEnabled(true);
        jTextFieldNanimal.requestFocus();
         }else{   
         pesodellote= Double.parseDouble(jTextFieldPeso.getText());
         redondear redon = new redondear();
         pesopromedio=pesodellote/Lista.size();
         pesoindividual=redon.redondearDecimales(pesopromedio, 2);
         jTextFieldPesoNeto.setText(pesoindividual.toString());
         }
         }
          }
         
        }catch(Exception ex){
         //JOptionPane.showMessageDialog(null,"Error" +ex); 
          jTextFieldPeso.setText("0");
          jTextFieldPeso.selectAll();
          jTextFieldPeso.requestFocus();
          jTextFieldMontoTotal.setText("");
        }
        
    }//GEN-LAST:event_jTextFieldPesoKeyReleased

    private void jTextFieldDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDetalleActionPerformed
        // TODO add your handling code here:
        try{
           if  (jRadioButtonIndividual.isSelected()==true){  
                jTextFieldPrecio.requestFocus();
           }else{
           jTextFieldNumerodelote.requestFocus();
           lotes lote = new lotes();
           jTextFieldNumerodelote.setText(lote.buscarultimolote().toString());
           }
        }catch(Exception ex){
         JOptionPane.showMessageDialog(null,"Error" +ex); 
        }
       
    }//GEN-LAST:event_jTextFieldDetalleActionPerformed

    private void jButtonGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonGuardarKeyPressed
        // TODO add your handling code here:
        try{
            /*
            evt.setSource((char) KeyEvent.VK_ENTER);
           if ((jTextFieldNanimal.getText().trim().length()==0) || (jTextFieldCodigoComprador.getText().trim().length()==0)|| (jTextFieldTipo.getText().trim().length()==0) || (jTextFieldColor.getText().trim().length()==0)
                 || (jTextFieldSexo.getText().trim().length()==0) || (jTextFieldFerrete.getText().trim().length()==0) || (jTextFieldNombredelcomprador.getText().trim().length()==0)|| (jTextFieldCeduladelcomprador.getText().trim().length()==0)
                   || (jTextFieldPesoNeto.getText().trim().length()==0)|| (jTextFieldPrecioPactado.getText().trim().length()==0)|| (jTextFieldMontoTotal.getText().trim().length()==0)){
            JOptionPane.showMessageDialog(null,"Para Poder realizar Esta Operacion Debe Completar La Informacion En Las Cajas De Textos");
           }else{
           subastas suba = new subastas();
           suba.guardarsubasta();
           suba.machos();
           suba.hembras();
           suba.totalmachoshembras();
           suba.buscarporsubastar();
           suba.tablesubastado();
            }
            */
            if (jRadioButtonIndividual.isSelected()==true){
           if ((jTextFieldNanimal.getText().trim().length()==0) || (jTextFieldCodigoComprador.getText().trim().length()==0)|| (jTextFieldTipo.getText().trim().length()==0) || (jTextFieldColor.getText().trim().length()==0)
                 || (jTextFieldSexo.getText().trim().length()==0) || (jTextFieldFerrete.getText().trim().length()==0) || (jTextFieldNombredelcomprador.getText().trim().length()==0)|| (jTextFieldCeduladelcomprador.getText().trim().length()==0)
                   || (jTextFieldPesoNeto.getText().trim().length()==0)|| (jTextFieldPrecioPactado.getText().trim().length()==0)|| (jTextFieldMontoTotal.getText().trim().length()==0)){
            JOptionPane.showMessageDialog(null,"Para Poder realizar Esta Operacion Debe Completar La Informacion En Las Cajas De Textos");
            jTextFieldNanimal.requestFocus();
           }else{
                        
           subastas suba = new subastas();
           suba.guardarsubasta();
           suba.machos();
           suba.hembras();
           suba.totalmachoshembras();
           suba.buscarporsubastar();
           suba.tablesubastado();
            }
               
           }
           
           if (this.jRadioButtonPorlote.isSelected()==true){
           if ((jTextFieldCodigoComprador.getText().trim().length()==0)|| (jTextFieldNombredelcomprador.getText().trim().length()==0)|| (jTextFieldCeduladelcomprador.getText().trim().length()==0)
              || (jTextFieldPesoNeto.getText().trim().length()==0)|| (jTextFieldPrecioPactado.getText().trim().length()==0)|| (jTextFieldMontoTotal.getText().trim().length()==0)){
            JOptionPane.showMessageDialog(null,"Para Poder realizar Esta Operacion Debe Completar La Informacion");
          
           }else{
           subastas suba = new subastas();
            
            suba.guardarsubastaporlote();
       
           suba.machos();
           suba.hembras();
           suba.totalmachoshembras();
           suba.buscarporsubastar();
           suba.tablesubastado();
            }
               
           } 
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null, "Error:"+ex);
        }
    }//GEN-LAST:event_jButtonGuardarKeyPressed

    private void jRadioButtonPorloteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPorloteActionPerformed
        // TODO add your handling code here:
        try{
        jTextFieldNanimal.setEnabled(false);
        jTextFieldCodigoComprador.requestFocus();
        jTextFieldNumerodelote.setEnabled(true);
       // jTextFieldNumerodelote.requestFocus();
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null, "Error:"+ex);
        }
    }//GEN-LAST:event_jRadioButtonPorloteActionPerformed

    private void jRadioButtonIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIndividualActionPerformed
        // TODO add your handling code here:
        try{
        jTextFieldNumerodelote.setText("");
        Lista.clear();
        jTextFieldNumerodelote.setEnabled(false);
        jTextFieldNanimal.setEnabled(true);
        jTextFieldNanimal.selectAll();
        jTextFieldNanimal.requestFocus();
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null, "Error:"+ex);
        }
    }//GEN-LAST:event_jRadioButtonIndividualActionPerformed

    private void jTextFieldNumerodeloteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumerodeloteActionPerformed
        // TODO add your handling code here:
          try{
      Integer c2=0,c3=0,c4=0,c5=0,c6=0;
      Integer v1=0,v2=0,v3=0,v4=0,v5=0,v6=0;
      subastas su = new subastas();
      cant=0;
      fer2=JOptionPane.showInputDialog (null,"Introdusca El Codigo Del Animal:");
      if(fer2==null||fer2.equals("")){  
      jTextFieldPrecio.requestFocus();
      }else{
      v1=su.verificaranimal(fer2, fecha);
      if (v1==1){
      Lista.add(fer2);   
      c2=1;
      }
      }  
      //segundo adicional
      if(c2==1){
       fer3=JOptionPane.showInputDialog (null,"Introdusca El Codigo Del Animal:");
      if(fer3==null||fer3.equals("")){  
      jTextFieldPrecio.requestFocus();
      }else{
      v2=su.verificaranimal(fer3, fecha);
      if (v2==1){
      Lista.add(fer3);
      c3=1;
      } 
      }
      }
      //2
      //tercero adicional
      if(c3==1){
      fer4=JOptionPane.showInputDialog (null,"Introdusca El Codigo Del Animal:");
      if(fer4==null||fer4.equals("")){  
      jTextFieldPrecio.requestFocus();
      }else{
     v3=su.verificaranimal(fer4, fecha);
      if (v3==1){
      Lista.add(fer4);
      c4=1;
      } 
      }
      }
      //3
      //cuarto adicional
      if(c4==1){
      fer5=JOptionPane.showInputDialog (null,"Introdusca El Codigo Del Animal:");
      if(fer5==null||fer5.equals("")){  
      jTextFieldPrecio.requestFocus();
      }else{
      v4=su.verificaranimal(fer5, fecha);
      if (v4==1){
      Lista.add(fer5);
      c5=1;
      } 
      }
      }
      //4
       //quinto adicional
      if(c5==1){
      fer6=JOptionPane.showInputDialog (null,"Introdusca El Codigo Del Animal:");
      if(fer6==null||fer6.equals("")){  
      jTextFieldPrecio.requestFocus();
      }else{
      v5=su.verificaranimal(fer6, fecha);
      if (v5==1){
      Lista.add(fer6);
      c6=1;
      } 
      }
      }
      // sexto adicional
      if(c6==1){
      fer7=JOptionPane.showInputDialog (null,"Introdusca El Codigo Del Animal:");
      if(fer7==null||fer7.equals("")){  
      jTextFieldPrecio.requestFocus();
      }else{
      v6=su.verificaranimal(fer7, fecha);
      if (v6==1){
      Lista.add(fer7);
      jTextFieldPrecio.requestFocus();
      //c6=1;
      } 
      }
      }
     cant=Lista.size();
      
      System.out.println(cant);
      System.out.println(Lista);
     // Lista.clear();
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null, "Error:   " +ex.getMessage());        
        }
    }//GEN-LAST:event_jTextFieldNumerodeloteActionPerformed

    private void jTextFieldNumerodeloteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumerodeloteKeyPressed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_jTextFieldNumerodeloteKeyPressed

    private void jButtonVerLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerLoteActionPerformed
        // TODO add your handling code here:
       try{
       if (Lista.size()<=1){
       JOptionPane.showMessageDialog(null, "El Proceso No Es Una Venta Por Lote, Para Ello Debe Tener Minimo Dos Animales");
       Lista.clear();
       }else{    
       Veranimalesenlote ver = new Veranimalesenlote();
       ver.setVisible(true);       
       lotes lo =new lotes();
       lo.mostrarlotes(fecha);
       jTextFieldPrecio.setText("");
       jTextFieldPeso.setText("");
       jTextFieldPesoNeto.setText("");
       jTextFieldPrecioPactado.setText("");
       jTextFieldMontoTotal.setText("");
       jTextFieldPrecio.requestFocus();
       }
       }catch(Exception ex){
       JOptionPane.showMessageDialog(null, "Error:   " +ex.getMessage());
       }
       
    }//GEN-LAST:event_jButtonVerLoteActionPerformed

    private void jTextFieldMontoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMontoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMontoTotalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   
    conectar conect = new conectar(); 
    conect.conexion();
  
       
            Calendar c1 = Calendar.getInstance();
      String  dia = Integer.toString(c1.get(Calendar.DAY_OF_MONTH));
      String  mes = Integer.toString(c1.get(Calendar.MONTH) + 1);
      String year = Integer.toString(c1.get(Calendar.YEAR));
      String Fecha = (year + "-" + mes+ "-" + dia);  
           
                      try {
                   
                    JasperReport jasperReport;
                    JasperPrint jasperPrint;
                
                     Map<String, Object> params = new HashMap<>();
                    String  ruta="C:\\SG-SOFT\\subastaganadera\\src\\ReportesSG\\" +  "compradoresdia.jrxml";  
                    jasperReport =JasperCompileManager.compileReport(ruta);
                    params.put("Fecha", Fecha);

                    jasperPrint = JasperFillManager.fillReport(jasperReport, params, conect.con);
                  JasperViewer.viewReport(jasperPrint, false);


                 } catch (Exception ex) {
                    System.err.println("Error JRException: " + ex.getMessage());
                 }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subastas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salir;
    private javax.swing.ButtonGroup buttonGroupLotes;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonLista;
    private javax.swing.JButton jButtonListaIndividual;
    private javax.swing.JButton jButtonNosubastado;
    private javax.swing.JButton jButtonVerLote;
    public static com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPrecioPactado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JRadioButton jRadioButtonIndividual;
    private javax.swing.JRadioButton jRadioButtonPorlote;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JTable jTableSubastados;
    public static javax.swing.JTextField jTextFieldCeduladelcomprador;
    public static javax.swing.JTextField jTextFieldCheques;
    public static javax.swing.JTextField jTextFieldCodigoComprador;
    public static javax.swing.JTextField jTextFieldColor;
    public static javax.swing.JTextField jTextFieldDetalle;
    public static javax.swing.JTextField jTextFieldFerrete;
    public static javax.swing.JTextField jTextFieldHembras;
    public static javax.swing.JTextField jTextFieldMachos;
    public static javax.swing.JTextField jTextFieldMontoTotal;
    public static javax.swing.JTextField jTextFieldNanimal;
    public static javax.swing.JTextField jTextFieldNombredelcomprador;
    public static javax.swing.JTextField jTextFieldNumerodelote;
    public static javax.swing.JTextField jTextFieldPeso;
    public static javax.swing.JTextField jTextFieldPesoNeto;
    public static javax.swing.JTextField jTextFieldPorsubastar;
    public static javax.swing.JTextField jTextFieldPrecio;
    public static javax.swing.JTextField jTextFieldPrecioPactado;
    public static javax.swing.JTextField jTextFieldSexo;
    public static javax.swing.JTextField jTextFieldTipo;
    public static javax.swing.JTextField jTextFieldTotaldeanimales;
    // End of variables declaration//GEN-END:variables
}
