/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;


import java.util.Date;
import Clases.traspasar;
import java.util.Calendar;
import javax.swing.JOptionPane;
/**
 *
 * @author Tserng
 */
public class Traspaso extends javax.swing.JFrame {
public static Integer identrada,nuevocodigo,idanimal,codigonuevo;
public static String fecha,nombre;
    /**
     * Creates new form Traspaso
     */
    public Traspaso() {
        initComponents();
        this.jDateChooserFecha.setDateFormatString("dd/MM/yyyy");
        Date date = new Date(); 
        this.jDateChooserFecha.setDate(date); 
        //ocultando columna del jtable 
        jTableTraspasos.getColumnModel().getColumn(8).setMaxWidth(8);
        jTableTraspasos.getColumnModel().getColumn(8).setMinWidth(8);
        jTableTraspasos.getColumnModel().getColumn(8).setPreferredWidth(8);
        //hasta aki 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableTraspasos = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButtonTodos = new javax.swing.JRadioButton();
        jRadioButtonNinguno = new javax.swing.JRadioButton();
        jRadioButtonVendedor = new javax.swing.JRadioButton();
        jRadioButtonComprador = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jTextFieldCodigodebusqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldNanimal = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDueno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombredueno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldApellidodueno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCeduladueno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButtonTraspasar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCodigonuevodueno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNombrenuevodueno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldApellidonuevodueno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCedulanuevodueno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Traspasos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTableTraspasos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableTraspasos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "# De Animal", "Tipo", "Sexo", "Color", "Peso", "Ferrete", "Cod Vendedor", "Seleccionar", "# De Entrada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableTraspasos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTraspasosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableTraspasos);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel12.setText("Seleccionar:");

        buttonGroup1.add(jRadioButtonTodos);
        jRadioButtonTodos.setText("Todos Los Seleccionados");
        jRadioButtonTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTodosActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonNinguno);
        jRadioButtonNinguno.setText("Ninguno");
        jRadioButtonNinguno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNingunoActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonVendedor);
        jRadioButtonVendedor.setText("Vendedor");
        jRadioButtonVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVendedorActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonComprador);
        jRadioButtonComprador.setText("Comprador");
        jRadioButtonComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCompradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jRadioButtonTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonNinguno))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jRadioButtonVendedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonComprador)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonNinguno)
                    .addComponent(jRadioButtonTodos)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonComprador)
                    .addComponent(jRadioButtonVendedor))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextFieldCodigodebusqueda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldCodigodebusqueda.setForeground(new java.awt.Color(255, 0, 0));
        jTextFieldCodigodebusqueda.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextFieldCodigodebusquedaPropertyChange(evt);
            }
        });
        jTextFieldCodigodebusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCodigodebusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigodebusquedaKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Filtrar Datos Por :Codigo");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Filtrar Datos Por :#Animal");

        jTextFieldNanimal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldNanimal.setForeground(new java.awt.Color(255, 51, 51));
        jTextFieldNanimal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNanimalKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNanimal, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCodigodebusqueda)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigodebusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNanimal, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel13))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jDateChooserFecha.setBackground(new java.awt.Color(204, 204, 204));
        jDateChooserFecha.setForeground(new java.awt.Color(51, 51, 51));
        jDateChooserFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("FECHA");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDateChooserFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel14)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Codigo");

        jTextFieldDueno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldDueno.setEnabled(false);

        jLabel4.setText("Nombre");

        jTextFieldNombredueno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldNombredueno.setEnabled(false);

        jLabel5.setText("Apellido");

        jTextFieldApellidodueno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldApellidodueno.setEnabled(false);

        jLabel6.setText("Cedula");

        jTextFieldCeduladueno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCeduladueno.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Dueño Actual ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldDueno, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCeduladueno))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldApellidodueno))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNombredueno)))))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDueno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombredueno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldApellidodueno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCeduladueno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonTraspasar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonTraspasar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/App-login-manager-icon.png"))); // NOI18N
        jButtonTraspasar.setText("Traspasar");
        jButtonTraspasar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTraspasarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Actions-trash-empty-icon.png"))); // NOI18N
        jButtonLimpiar.setText("Nuevo");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Apps-Dialog-Logout-icon.png"))); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonTraspasar, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addComponent(jButtonLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonTraspasar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Codigo");

        jTextFieldCodigonuevodueno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldCodigonuevodueno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigonuevoduenoActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre");

        jTextFieldNombrenuevodueno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldNombrenuevodueno.setEnabled(false);

        jLabel9.setText("Apellido");

        jTextFieldApellidonuevodueno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldApellidonuevodueno.setEnabled(false);

        jLabel10.setText("Cedula");

        jTextFieldCedulanuevodueno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCedulanuevodueno.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Nuevo Dueño ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNombrenuevodueno, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(16, 16, 16)
                        .addComponent(jTextFieldCodigonuevodueno, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldApellidonuevodueno)
                            .addComponent(jTextFieldCedulanuevodueno))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldCodigonuevodueno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNombrenuevodueno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel9))
                    .addComponent(jTextFieldApellidonuevodueno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldCedulanuevodueno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodigodebusquedaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextFieldCodigodebusquedaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigodebusquedaPropertyChange

    private void jTextFieldCodigodebusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigodebusquedaKeyReleased
        // TODO add your handling code here:
     
        try {
          String codigo= jTextFieldCodigodebusqueda.getText();
           traspasar tr= new traspasar();
            if (this.jTextFieldCodigodebusqueda.getText().trim().length()==0){
            tr.buscarparatraspaso();
            jRadioButtonVendedor.setSelected(true);
            }else{
            tr.buscarparatraspasofiltro(codigo);
            }
            
            evt.consume();      
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Error" +ex.getMessage());
            }
    }//GEN-LAST:event_jTextFieldCodigodebusquedaKeyReleased

    private void jTextFieldCodigodebusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigodebusquedaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigodebusquedaKeyTyped

    private void jTableTraspasosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTraspasosMouseClicked
        // TODO add your handling code here:
        
      try{
      Integer codigo;    
      Integer i =Traspaso.jTableTraspasos.getSelectedRow();
      //-----obtener la fecha----------------------
      String  dia = Integer.toString(Traspaso.jDateChooserFecha.getCalendar().get(Calendar.DAY_OF_MONTH));
      String  mes = Integer.toString(Traspaso.jDateChooserFecha.getCalendar().get(Calendar.MONTH) + 1);
      String year = Integer.toString(Traspaso.jDateChooserFecha.getCalendar().get(Calendar.YEAR));
      fecha = (year + "-" + mes+ "-" + dia);         
     //---------fin de obtener la fecha
      //nuevocodigo= Integer.parseInt(jTextFieldCodigonuevodueno.getText());
      idanimal=(Integer)Traspaso.jTableTraspasos.getValueAt(i, 0);
      codigo = (Integer) Traspaso.jTableTraspasos.getValueAt(i, 6);
      identrada=(Integer)Traspaso.jTableTraspasos.getValueAt(i, 8); 
      nombre=jTextFieldNombrenuevodueno.getText() + " " + jTextFieldApellidonuevodueno.getText();
      traspasar tras=new traspasar();
      tras.buscardueno(codigo);
      
      }catch(Exception ex){
      JOptionPane.showMessageDialog(null,"Error" +ex);
      }
        
       
    }//GEN-LAST:event_jTableTraspasosMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        traspasar tras = new traspasar();
        tras.buscarparatraspaso();
        jRadioButtonNinguno.setSelected(true);
        jRadioButtonVendedor.setSelected(true);
    }//GEN-LAST:event_formWindowOpened

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldCodigonuevoduenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigonuevoduenoActionPerformed
        // TODO add your handling code here:
        try{
          Integer x = Integer.parseInt(jTextFieldCodigonuevodueno.getText());
         Integer y = Integer.parseInt(jTextFieldDueno.getText()); 
         if (x==y){
            JOptionPane.showMessageDialog(null,"El Animal Ya Le Pertenece A Este Ganadero");  
         }else{
        codigonuevo= Integer.parseInt(jTextFieldCodigonuevodueno.getText());
        traspasar tra = new traspasar();        
        tra.buscarnuevodueno(codigonuevo);
        
         }
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Error" +ex);
        }
        
    }//GEN-LAST:event_jTextFieldCodigonuevoduenoActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        try{
            jTextFieldDueno.setText("");
            jTextFieldNombredueno.setText("");
            jTextFieldApellidodueno.setText("");
            jTextFieldCeduladueno.setText("");
            jTextFieldNombrenuevodueno.setText("");
            jTextFieldApellidonuevodueno.setText("");
            jTextFieldCedulanuevodueno.setText("");
            jTextFieldCodigonuevodueno.setText("");
            jTextFieldCodigonuevodueno.setEnabled(true);
        }catch(Exception ex){
         JOptionPane.showMessageDialog(null,"Error" +ex);
        }
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonTraspasarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTraspasarActionPerformed
        // TODO add your handling code here:
        try{
            
         if (jTextFieldDueno.getText().trim().length()==0 || jTextFieldCodigonuevodueno.getText().trim().length()==0){
         JOptionPane.showMessageDialog(null, "No se Puede Realizar EL Proceso Verifique Los Datos");
         }else{               
        traspasar tras=new traspasar();   
        if((jRadioButtonNinguno.isSelected()==true) && (jRadioButtonVendedor.isSelected()==true)) {
        traspasar tra = new traspasar();        
        tra.guardartraspaso(identrada, fecha, idanimal, codigonuevo);
        tra.buscarparatraspaso();
            jTextFieldDueno.setText("");
            jTextFieldNombredueno.setText("");
            jTextFieldApellidodueno.setText("");
            jTextFieldCeduladueno.setText("");
            jTextFieldNombrenuevodueno.setText("");
            jTextFieldApellidonuevodueno.setText("");
            jTextFieldCedulanuevodueno.setText("");
            jTextFieldCodigonuevodueno.setText("");
            jTextFieldCodigonuevodueno.setEnabled(true);
            
        }else if ((jRadioButtonTodos.isSelected()==true) && (jRadioButtonVendedor.isSelected()==true)){
            
    for (int i = 0; i < jTableTraspasos.getRowCount(); i++) {
    
     boolean seleccion = (boolean)  (jTableTraspasos.getValueAt(i, 7));
   // String estado = String.valueOf(jTableTraspasos.getValueAt(i, 7));
   // boolean seleccion = Boolean.valueOf(estado);
    if(seleccion==true){
       Integer codigo;    
      //Integer i =Traspaso.jTableTraspasos.getSelectedRow();
      //-----obtener la fecha----------------------
      String  dia = Integer.toString(Traspaso.jDateChooserFecha.getCalendar().get(Calendar.DAY_OF_MONTH));
      String  mes = Integer.toString(Traspaso.jDateChooserFecha.getCalendar().get(Calendar.MONTH) + 1);
      String year = Integer.toString(Traspaso.jDateChooserFecha.getCalendar().get(Calendar.YEAR));
      fecha = (year + "-" + mes+ "-" + dia);         
     //---------fin de obtener la fecha
      //nuevocodigo= Integer.parseInt(jTextFieldCodigonuevodueno.getText());
      idanimal=(Integer)Traspaso.jTableTraspasos.getValueAt(i, 0);
      codigo = (Integer) Traspaso.jTableTraspasos.getValueAt(i, 6);
      identrada=(Integer)Traspaso.jTableTraspasos.getValueAt(i, 8);   
      
      tras.buscardueno(codigo);
      tras.guardartraspasoselecionados(identrada, fecha, idanimal, codigonuevo);
      
            
    }else{
        //JOptionPane.showMessageDialog(null,"No Hay Elementos Seleccionados Para Traspazar");
    }
      }
    tras.buscarparatraspaso();
    JOptionPane.showMessageDialog(null, "Registro De Traspaso Realizado Satisfactoriamente");
    jTextFieldDueno.setText("");
            jTextFieldNombredueno.setText("");
            jTextFieldApellidodueno.setText("");
            jTextFieldCeduladueno.setText("");
            jTextFieldNombrenuevodueno.setText("");
            jTextFieldApellidonuevodueno.setText("");
            jTextFieldCedulanuevodueno.setText("");
            jTextFieldCodigonuevodueno.setText("");
            jTextFieldCodigonuevodueno.setEnabled(true);
    jRadioButtonNinguno.setSelected(true);
        } else if ((jRadioButtonNinguno.isSelected()==true) && (jRadioButtonComprador.isSelected()==true)){
         traspasar tra = new traspasar();
        nombre=jTextFieldNombrenuevodueno.getText() + " " + jTextFieldApellidonuevodueno.getText(); 
        tra.guardartraspasocomprador(identrada, fecha, idanimal, codigonuevo, nombre);
        tra.buscarparatraspasocomprador();
            jTextFieldDueno.setText("");
            jTextFieldNombredueno.setText("");
            jTextFieldApellidodueno.setText("");
            jTextFieldCeduladueno.setText("");
            jTextFieldNombrenuevodueno.setText("");
            jTextFieldApellidonuevodueno.setText("");
            jTextFieldCedulanuevodueno.setText("");
            jTextFieldCodigonuevodueno.setText("");
            jTextFieldCodigonuevodueno.setEnabled(true);   
            
         }else if ((jRadioButtonTodos.isSelected()==true) && (jRadioButtonComprador.isSelected()==true)){
           for (int i = 0; i < jTableTraspasos.getRowCount(); i++) {
    
     boolean seleccion = (boolean)  (jTableTraspasos.getValueAt(i, 7));
   // String estado = String.valueOf(jTableTraspasos.getValueAt(i, 7));
   // boolean seleccion = Boolean.valueOf(estado);
    if(seleccion==true){
       Integer codigo;    
      //Integer i =Traspaso.jTableTraspasos.getSelectedRow();
      //-----obtener la fecha----------------------
      String  dia = Integer.toString(Traspaso.jDateChooserFecha.getCalendar().get(Calendar.DAY_OF_MONTH));
      String  mes = Integer.toString(Traspaso.jDateChooserFecha.getCalendar().get(Calendar.MONTH) + 1);
      String year = Integer.toString(Traspaso.jDateChooserFecha.getCalendar().get(Calendar.YEAR));
      fecha = (year + "-" + mes+ "-" + dia);         
     //---------fin de obtener la fecha
      //nuevocodigo= Integer.parseInt(jTextFieldCodigonuevodueno.getText());
      idanimal=(Integer)Traspaso.jTableTraspasos.getValueAt(i, 0);
      codigo = (Integer) Traspaso.jTableTraspasos.getValueAt(i, 6);
      identrada=(Integer)Traspaso.jTableTraspasos.getValueAt(i, 8);        
      tras.buscardueno(codigo);
      nombre=jTextFieldNombrenuevodueno.getText() + " " + jTextFieldApellidonuevodueno.getText();
      tras.guardartraspasoselecionadoscomprador(identrada, fecha, idanimal, codigonuevo, nombre);
      
            
    }else{
        //JOptionPane.showMessageDialog(null,"No Hay Elementos Seleccionados Para Traspazar");
    }
      } 
           JOptionPane.showMessageDialog(null, "Registro De Traspaso Realizado Satisfactoriamente");
           tras.buscarparatraspasocomprador();
           jTextFieldDueno.setText("");
            jTextFieldNombredueno.setText("");
            jTextFieldApellidodueno.setText("");
            jTextFieldCeduladueno.setText("");
            jTextFieldNombrenuevodueno.setText("");
            jTextFieldApellidonuevodueno.setText("");
            jTextFieldCedulanuevodueno.setText("");
            jTextFieldCodigonuevodueno.setText("");
            jTextFieldCodigonuevodueno.setEnabled(true);
         }
         }
        }catch(Exception ex){        
         JOptionPane.showMessageDialog(null,"Error" +ex.getMessage());
        }
        
    }//GEN-LAST:event_jButtonTraspasarActionPerformed
   
    private void jRadioButtonTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTodosActionPerformed
        // TODO add your handling code here:
        try{
       traspasar tras = new traspasar();
       Integer codigo = (Integer) Traspaso.jTableTraspasos.getValueAt(0, 6);       
      
      tras.buscardueno(codigo);    
        for (int i = 0; i < jTableTraspasos.getRowCount(); i++) {
          jTableTraspasos.setValueAt(true,i, 7);
        }
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Error" +ex.getMessage());
        }
        
    }//GEN-LAST:event_jRadioButtonTodosActionPerformed

    private void jRadioButtonNingunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNingunoActionPerformed
        // TODO add your handling code here:
         try{
        for (int i = 0; i < jTableTraspasos.getRowCount(); i++) {
          jTableTraspasos.setValueAt(null,i, 7);
        }
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Error" +ex.getMessage());
        }
    }//GEN-LAST:event_jRadioButtonNingunoActionPerformed

    private void jRadioButtonCompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCompradorActionPerformed
        // TODO add your handling code here:
        try{
        traspasar tra = new traspasar();
        tra.buscarparatraspasocomprador();
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Error" +ex.getMessage());        
        }
    }//GEN-LAST:event_jRadioButtonCompradorActionPerformed

    private void jRadioButtonVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVendedorActionPerformed
        // TODO add your handling code here:
        try{
        traspasar tra = new traspasar();
        tra.buscarparatraspaso();
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Error" +ex.getMessage());        
        }
    }//GEN-LAST:event_jRadioButtonVendedorActionPerformed

    private void jTextFieldNanimalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNanimalKeyReleased
        // TODO add your handling code here:
        try {
          String nanimal= jTextFieldNanimal.getText();
           traspasar tr= new traspasar();
            if (this.jTextFieldNanimal.getText().trim().length()==0){
            tr.buscarparatraspaso();
            jRadioButtonVendedor.setSelected(true);
            }else{
            tr.buscarparatraspasofiltronanimal(nanimal);
            }
            
            evt.consume();      
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Error" +ex.getMessage());
            }
    }//GEN-LAST:event_jTextFieldNanimalKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Traspaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Traspaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Traspaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Traspaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Traspaso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonTraspasar;
    public static com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButtonComprador;
    private javax.swing.JRadioButton jRadioButtonNinguno;
    private javax.swing.JRadioButton jRadioButtonTodos;
    private javax.swing.JRadioButton jRadioButtonVendedor;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTableTraspasos;
    public static javax.swing.JTextField jTextFieldApellidodueno;
    public static javax.swing.JTextField jTextFieldApellidonuevodueno;
    public static javax.swing.JTextField jTextFieldCeduladueno;
    public static javax.swing.JTextField jTextFieldCedulanuevodueno;
    public static javax.swing.JTextField jTextFieldCodigodebusqueda;
    public static javax.swing.JTextField jTextFieldCodigonuevodueno;
    public static javax.swing.JTextField jTextFieldDueno;
    private javax.swing.JTextField jTextFieldNanimal;
    public static javax.swing.JTextField jTextFieldNombredueno;
    public static javax.swing.JTextField jTextFieldNombrenuevodueno;
    // End of variables declaration//GEN-END:variables
}
