/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sg.soft;
import Clases.conectar;
import Interfaces.AnimalesSubastado;
import Interfaces.Bancos;
import Interfaces.Cheques;
import Interfaces.Clientes;
import Interfaces.Conciliacion;
import Interfaces.Depositos;
import Interfaces.Entradas;
import Interfaces.EstadisticaGeneral;
import Interfaces.FacturarC;
import Interfaces.FacturarV;
import Interfaces.ImprimirConciliacion;
import Interfaces.Listadenotas;
import Interfaces.Listadodedepositos;
import Interfaces.ListarVentas;
import Interfaces.Listarentrada;
import Interfaces.MantChk;
import Interfaces.MantDepositos;
import Interfaces.MantNotas;
import Interfaces.NotasDC;
import Interfaces.Proveedor;
import Interfaces.ReciboCaja;
import Interfaces.Recibos;
import Interfaces.RegCaja;
import Interfaces.Subastas;
import Interfaces.Traspaso;
import Interfaces.RptCuentasxPagar;
import Interfaces.Usuarios;
import Interfaces.ReporteCheques;
import Interfaces.Resumendecompra;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.util.Calendar;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Juan
 */
public class Principal extends javax.swing.JFrame {
JFileChooser RealizarBackupMySQL=new JFileChooser();
    conectar con;          
 
    /**
     * Creates new form Principal
     */
    public Principal() {

        initComponents();

    }
    
    private void close(){
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?",
                "Salir del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            System.exit(0);
    }      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        BP01 = new javax.swing.JButton();
        BP02 = new javax.swing.JButton();
        BP05 = new javax.swing.JButton();
        BP03 = new javax.swing.JButton();
        BP04 = new javax.swing.JButton();
        BP06 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MA01 = new javax.swing.JMenuItem();
        MA02 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MA03 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MB01 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        MB02 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        MB03 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        MB04 = new javax.swing.JMenu();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        MB05 = new javax.swing.JMenu();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        MB06 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MR01 = new javax.swing.JMenu();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemProveedores = new javax.swing.JMenuItem();
        jMenuItemCuentasbancarias = new javax.swing.JMenuItem();
        jMenuItemListadeusuarios = new javax.swing.JMenuItem();
        MR02 = new javax.swing.JMenu();
        jMenuItemEntradasanimales = new javax.swing.JMenuItem();
        MR03 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItemResumenVentas = new javax.swing.JMenuItem();
        MR04 = new javax.swing.JMenu();
        jMenuItemListarcheques = new javax.swing.JMenuItem();
        jMenuItemDepositos = new javax.swing.JMenuItem();
        jMenuItemNotas = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        MR05 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        MC01 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem14 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem15.setText("jMenuItem15");

        jMenuItem32.setText("jMenuItem32");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SG-SOFT - SUBASTAS  GANADERAS");
        setMaximumSize(new java.awt.Dimension(1182, 765));
        setMinimumSize(new java.awt.Dimension(1182, 765));
        setPreferredSize(new java.awt.Dimension(1182, 765));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        BP01.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BP01.setForeground(new java.awt.Color(0, 102, 102));
        BP01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Add-Folder-icon.png"))); // NOI18N
        BP01.setText("ENTRADAS");
        BP01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BP01ActionPerformed(evt);
            }
        });
        getContentPane().add(BP01);
        BP01.setBounds(40, 160, 270, 145);

        BP02.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BP02.setForeground(new java.awt.Color(0, 102, 102));
        BP02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Gavel-Law-icon (1).png"))); // NOI18N
        BP02.setText("SUBASTAS");
        BP02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BP02ActionPerformed(evt);
            }
        });
        getContentPane().add(BP02);
        BP02.setBounds(350, 160, 270, 145);

        BP05.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BP05.setForeground(new java.awt.Color(0, 102, 102));
        BP05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/peer-to-peer-icon (2).png"))); // NOI18N
        BP05.setText("TRASPASOS");
        BP05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BP05ActionPerformed(evt);
            }
        });
        getContentPane().add(BP05);
        BP05.setBounds(40, 520, 270, 145);

        BP03.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BP03.setForeground(new java.awt.Color(0, 102, 102));
        BP03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/shop-cart-apply-icon.png"))); // NOI18N
        BP03.setText("COMPRAS");
        BP03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BP03ActionPerformed(evt);
            }
        });
        getContentPane().add(BP03);
        BP03.setBounds(40, 340, 270, 145);

        BP04.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BP04.setForeground(new java.awt.Color(0, 102, 102));
        BP04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Invoice-icon.png"))); // NOI18N
        BP04.setText("VENTAS");
        BP04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BP04ActionPerformed(evt);
            }
        });
        getContentPane().add(BP04);
        BP04.setBounds(350, 340, 270, 145);

        BP06.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BP06.setForeground(new java.awt.Color(0, 102, 102));
        BP06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Pay-Per-Click-icon.png"))); // NOI18N
        BP06.setText("CHEQUES");
        BP06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BP06ActionPerformed(evt);
            }
        });
        getContentPane().add(BP06);
        BP06.setBounds(350, 520, 270, 145);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/run-icon.png"))); // NOI18N
        jButton6.setToolTipText("SALIR DEL SISTEMA");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setIconTextGap(-3);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1110, 40, 50, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Desarrolladores: Lic. Juan C. Ducreux; Lic. Joseph Yn Tserng; Cel. 67309619; email: juanducreux@hotmail.com");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 690, 580, 14);

        usuario.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        usuario.setForeground(new java.awt.Color(0, 153, 153));
        usuario.setText("JUAN DUCREUX");
        getContentPane().add(usuario);
        usuario.setBounds(1000, 34, 140, 20);

        tipo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        tipo.setForeground(new java.awt.Color(0, 153, 153));
        tipo.setText("ADMINISTRADOR");
        getContentPane().add(tipo);
        tipo.setBounds(1000, 60, 140, 13);

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/PORTADA 4.JPG"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1177, 758));
        jLabel1.setMinimumSize(new java.awt.Dimension(1177, 758));
        jLabel1.setPreferredSize(new java.awt.Dimension(1177, 758));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -70, 1470, 870);

        jMenu1.setText("Archivo     ");

        MA01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/user_red.png"))); // NOI18N
        MA01.setText("Clientes");
        MA01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MA01ActionPerformed(evt);
            }
        });
        jMenu1.add(MA01);

        MA02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Actions-list-add-user-icon.png"))); // NOI18N
        MA02.setText("Proveedores");
        MA02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MA02ActionPerformed(evt);
            }
        });
        jMenu1.add(MA02);
        jMenu1.add(jSeparator1);

        MA03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Database-Backup-icon.png"))); // NOI18N
        MA03.setText("Respaldo");
        MA03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MA03ActionPerformed(evt);
            }
        });
        jMenu1.add(MA03);
        jMenu1.add(jSeparator2);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Perspective-Button-Shutdown-icon.png"))); // NOI18N
        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Banco     ");

        MB01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Money-icon.png"))); // NOI18N
        MB01.setText("Caja Menuda");

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem8.setForeground(new java.awt.Color(255, 102, 0));
        jMenuItem8.setText("Crear");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        MB01.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem9.setForeground(new java.awt.Color(255, 102, 0));
        jMenuItem9.setText("Registros de Caja");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        MB01.add(jMenuItem9);
        MB01.add(jSeparator7);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem7.setForeground(new java.awt.Color(255, 102, 0));
        jMenuItem7.setText("Abonos a Facturas");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        MB01.add(jMenuItem7);

        jMenu2.add(MB01);

        MB02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/money-icon (1).png"))); // NOI18N
        MB02.setText("Cuentas");
        MB02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MB02ActionPerformed(evt);
            }
        });
        jMenu2.add(MB02);
        jMenu2.add(jSeparator3);

        MB03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/cheque-icon.png"))); // NOI18N
        MB03.setText("Cheques");

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem12.setForeground(new java.awt.Color(255, 102, 0));
        jMenuItem12.setText("Crear");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        MB03.add(jMenuItem12);

        jMenuItem31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem31.setForeground(new java.awt.Color(255, 102, 0));
        jMenuItem31.setText("Mantenimiento");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        MB03.add(jMenuItem31);

        jMenu2.add(MB03);

        MB04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/safe-icon.png"))); // NOI18N
        MB04.setText("Depositos");

        jMenuItem33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem33.setForeground(new java.awt.Color(255, 102, 0));
        jMenuItem33.setText("Registrar");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        MB04.add(jMenuItem33);

        jMenuItem34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem34.setForeground(new java.awt.Color(255, 102, 0));
        jMenuItem34.setText("Mantenimiento");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        MB04.add(jMenuItem34);

        jMenu2.add(MB04);

        MB05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/Bank-icon.png"))); // NOI18N
        MB05.setText("Notas Debito/Credito");

        jMenuItem35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem35.setForeground(new java.awt.Color(255, 102, 0));
        jMenuItem35.setText("Registrar");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        MB05.add(jMenuItem35);

        jMenuItem36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem36.setForeground(new java.awt.Color(255, 102, 0));
        jMenuItem36.setText("Mantenimiento");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        MB05.add(jMenuItem36);

        jMenu2.add(MB05);
        jMenu2.add(jSeparator4);

        MB06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/cow-history-icon.png"))); // NOI18N
        MB06.setText("Conciliacion");
        MB06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MB06ActionPerformed(evt);
            }
        });
        jMenu2.add(MB06);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Reportes     ");

        MR01.setText("Listas de Maestros");

        jMenuItemClientes.setText("Lista de Clientes");
        jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientesActionPerformed(evt);
            }
        });
        MR01.add(jMenuItemClientes);

        jMenuItemProveedores.setText("Lista de Proveedores");
        jMenuItemProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProveedoresActionPerformed(evt);
            }
        });
        MR01.add(jMenuItemProveedores);

        jMenuItemCuentasbancarias.setText("Lista de Cuentas Bancarias");
        jMenuItemCuentasbancarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCuentasbancariasActionPerformed(evt);
            }
        });
        MR01.add(jMenuItemCuentasbancarias);

        jMenuItemListadeusuarios.setText("Lista de Usuarios");
        jMenuItemListadeusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadeusuariosActionPerformed(evt);
            }
        });
        MR01.add(jMenuItemListadeusuarios);

        jMenu4.add(MR01);

        MR02.setText("Entradas");
        MR02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MR02ActionPerformed(evt);
            }
        });

        jMenuItemEntradasanimales.setText("Animales Registrados");
        jMenuItemEntradasanimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEntradasanimalesActionPerformed(evt);
            }
        });
        MR02.add(jMenuItemEntradasanimales);

        jMenu4.add(MR02);

        MR03.setText("Subastas");

        jMenuItem16.setText("Animales Subastados");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        MR03.add(jMenuItem16);

        jMenuItem17.setText("Estadistica General");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        MR03.add(jMenuItem17);
        MR03.add(jSeparator8);

        jMenuItem22.setText("Resumen de Compras");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        MR03.add(jMenuItem22);

        jMenuItemResumenVentas.setText("Resumen de Ventas");
        jMenuItemResumenVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemResumenVentasActionPerformed(evt);
            }
        });
        MR03.add(jMenuItemResumenVentas);

        jMenu4.add(MR03);

        MR04.setText("Banco");

        jMenuItemListarcheques.setText("Listas Cheques");
        jMenuItemListarcheques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarchequesActionPerformed(evt);
            }
        });
        MR04.add(jMenuItemListarcheques);

        jMenuItemDepositos.setText("Listas Depositos");
        jMenuItemDepositos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDepositosActionPerformed(evt);
            }
        });
        MR04.add(jMenuItemDepositos);

        jMenuItemNotas.setText("Listas Notas Debito/Credito");
        jMenuItemNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNotasActionPerformed(evt);
            }
        });
        MR04.add(jMenuItemNotas);

        jMenuItem24.setText("Conciliaciones Bancarias");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        MR04.add(jMenuItem24);

        jMenuItem19.setText("Movimientos de Cuenta");
        MR04.add(jMenuItem19);

        jMenu4.add(MR04);

        MR05.setText("Otros Listados");

        jMenuItem20.setText("Cuentas x Cobrar");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        MR05.add(jMenuItem20);

        jMenuItem21.setText("Compras x Proceso");
        MR05.add(jMenuItem21);

        jMenu4.add(MR05);

        jMenuBar1.add(jMenu4);

        MC01.setText("Configuracion     ");

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/App-login-manager-icon.png"))); // NOI18N
        jMenuItem11.setText("Usuarios");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        MC01.add(jMenuItem11);
        MC01.add(jSeparator5);

        jMenuBar1.add(MC01);

        jMenu6.setText("Ayuda");

        jMenuItem13.setText("Contenido");
        jMenu6.add(jMenuItem13);
        jMenu6.add(jSeparator6);

        jMenuItem14.setText("Acerca De...");
        jMenu6.add(jMenuItem14);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MA01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MA01ActionPerformed
        Clientes cliente = new Clientes();
        cliente.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_MA01ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        Usuarios user = new Usuarios();
        user.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void MA03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MA03ActionPerformed
GenerarBackupMySQL();

    }//GEN-LAST:event_MA03ActionPerformed
void GenerarBackupMySQL(){
        int resp;
        Calendar c=Calendar.getInstance();
        String fecha=String.valueOf(c.get(Calendar.DATE));
        fecha=fecha+"-"+String.valueOf(c.get(Calendar.MONTH) + 1);
      fecha=fecha+"-"+String.valueOf(c.get(Calendar.YEAR));
      //String nombre=this.jTextField1.getText();
      //String pass=this.jTextField2.getText();
        resp=RealizarBackupMySQL.showSaveDialog(this);//JFileChooser de nombre RealizarBackupMySQL
        if (resp==JFileChooser.APPROVE_OPTION) {//Si el usuario presiona aceptar; se genera el Backup
            try{
                Runtime runtime = Runtime.getRuntime();
                File backupFile = new File(String.valueOf(RealizarBackupMySQL.getSelectedFile().toString())
                        +"_"+fecha+".sql");
                InputStreamReader irs;
                BufferedReader br;
                try (FileWriter fw = new FileWriter(backupFile)) {
                    Process child = runtime.exec("C:\\Program Files\\MySQL\\MySQL Server 5.7\\bin\\mysqldump --opt --password=root --user=root "
                            + "sg-soft");
                    irs = new InputStreamReader(child.getInputStream());
                    br = new BufferedReader(irs);
                    String line;
                    while( (line=br.readLine()) != null ) {
                        fw.write(line + "\n");
                    }
                }
                irs.close();
                br.close();

                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error no se genero el archivo por el siguiente motivo:"+e.getMessage(), "Verificar",JOptionPane.ERROR_MESSAGE);
            }
            JOptionPane.showMessageDialog(null, "RESPALDO REALIZADO CORRECTAMENTE","Verificar",JOptionPane.INFORMATION_MESSAGE);
        } else if (resp==JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null,"PROCESO DE RESPALDO DE LA BASE DE DATOS CANCELADO");
        }
    }
    private void BP06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BP06ActionPerformed
        Cheques ch = new Cheques();
        ch.setVisible(true); 
        
    }//GEN-LAST:event_BP06ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
         if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?",
                "Salir del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void BP01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BP01ActionPerformed
        Entradas ent = new Entradas();
        ent.setVisible(true); 
    }//GEN-LAST:event_BP01ActionPerformed

    private void BP02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BP02ActionPerformed
        Subastas suba = new Subastas();
        suba.setVisible(true); 
    }//GEN-LAST:event_BP02ActionPerformed

    private void BP05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BP05ActionPerformed
Traspaso cambio = new Traspaso ();
cambio.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_BP05ActionPerformed

    private void BP04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BP04ActionPerformed
 FacturarV rcbo = new FacturarV();
rcbo.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_BP04ActionPerformed

    private void BP03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BP03ActionPerformed
  FacturarC fact = new FacturarC();
fact.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_BP03ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
  if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?",
                "Salir del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
close();
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void MA02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MA02ActionPerformed
             Proveedor fact = new Proveedor();
fact.setVisible(true); 
    }//GEN-LAST:event_MA02ActionPerformed

    private void MB02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MB02ActionPerformed
                    Bancos fact = new Bancos();
fact.setVisible(true); 
    }//GEN-LAST:event_MB02ActionPerformed

    private void MB06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MB06ActionPerformed
                                  Conciliacion fact = new Conciliacion();
fact.setVisible(true); 
    }//GEN-LAST:event_MB06ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
               MantChk fact = new MantChk();
fact.setVisible(true);
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
              Cheques ch = new Cheques();
        ch.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
                       NotasDC cliente = new NotasDC();
        cliente.setVisible(true); 
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
                 Depositos fact = new Depositos();
fact.setVisible(true); 
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
         MantDepositos fact = new MantDepositos();
fact.setVisible(true); 
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
       MantNotas fact = new MantNotas();
       fact.setVisible(true); 
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
        // TODO add your handling code here:
         conectar conect = new conectar(); 
         conect.conexion();
         try{
           
   // Map<String, Object> params = new HashMap<String, Object>();
      String  ruta="C:\\SG-SOFT\\subastaganadera\\src\\ReportesSG\\" +  "Clientes.jrxml";  
    JasperReport jasperReport =JasperCompileManager.compileReport(ruta);
    JasperPrint jasperPrint =JasperFillManager.fillReport(jasperReport,null, conect.con);
    JasperViewer.viewReport(jasperPrint, false);
            
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Error" +ex.getMessage());
        
        }finally{
         conect.desconectar();
         }
    }//GEN-LAST:event_jMenuItemClientesActionPerformed

    private void jMenuItemProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProveedoresActionPerformed
        // TODO add your handling code here:
        conectar conect = new conectar(); 
        conect.conexion();
        try{      
    // Map<String, Object> params = new HashMap<String, Object>();  
    String  ruta="C:\\SG-SOFT\\subastaganadera\\src\\ReportesSG\\" +  "Proveedores.jrxml";  
    JasperReport jasperReport =JasperCompileManager.compileReport(ruta);
    JasperPrint jasperPrint =JasperFillManager.fillReport(jasperReport,null, conect.con);
    JasperViewer.viewReport(jasperPrint, false);
            
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Error" +ex.getMessage());
        
        }finally{
        conect.desconectar();
        }
    }//GEN-LAST:event_jMenuItemProveedoresActionPerformed

    private void jMenuItemCuentasbancariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCuentasbancariasActionPerformed
        // TODO add your handling code here:
         conectar conect = new conectar(); 
        conect.conexion();
        try{      
    // Map<String, Object> params = new HashMap<String, Object>();  
    String  ruta="C:\\SG-SOFT\\subastaganadera\\src\\ReportesSG\\" +  "Cuentasbancarias.jrxml";  
    JasperReport jasperReport =JasperCompileManager.compileReport(ruta);
    JasperPrint jasperPrint =JasperFillManager.fillReport(jasperReport,null, conect.con);
    JasperViewer.viewReport(jasperPrint, false);
            
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Error" +ex.getMessage());
        
        }finally{
        conect.desconectar();
        }
        
    }//GEN-LAST:event_jMenuItemCuentasbancariasActionPerformed

    private void jMenuItemListadeusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadeusuariosActionPerformed
        // TODO add your handling code here:
        conectar conect = new conectar(); 
        conect.conexion();
        try{      
    // Map<String, Object> params = new HashMap<String, Object>();  
    String  ruta="C:\\SG-SOFT\\subastaganadera\\src\\ReportesSG\\" +  "Usuarios.jrxml";  
    JasperReport jasperReport =JasperCompileManager.compileReport(ruta);
    JasperPrint jasperPrint =JasperFillManager.fillReport(jasperReport,null, conect.con);
    JasperViewer.viewReport(jasperPrint, false);
            
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Error" +ex.getMessage());
        
        }finally{
        conect.desconectar();
        }
    }//GEN-LAST:event_jMenuItemListadeusuariosActionPerformed

    private void jMenuItemListarchequesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarchequesActionPerformed
        // TODO add your handling code here:
        ReporteCheques re = new ReporteCheques();
        re.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemListarchequesActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
               ImprimirConciliacion fact = new ImprimirConciliacion ();
       fact.setVisible(true); 
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItemDepositosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDepositosActionPerformed
        // TODO add your handling code here:
        Listadodedepositos list = new Listadodedepositos();
        list.setVisible(true);
    }//GEN-LAST:event_jMenuItemDepositosActionPerformed

    private void jMenuItemNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNotasActionPerformed
        // TODO add your handling code here:
        Listadenotas list = new Listadenotas();
        list.setVisible(true);
    }//GEN-LAST:event_jMenuItemNotasActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
             ReciboCaja fact = new ReciboCaja();
       fact.setVisible(true); 
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
          RegCaja fact = new RegCaja();
       fact.setVisible(true); 
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Recibos fact = new Recibos();
       fact.setVisible(true); 
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void MR02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MR02ActionPerformed
        // TODO add your handling code here:
              
    }//GEN-LAST:event_MR02ActionPerformed

    private void jMenuItemEntradasanimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEntradasanimalesActionPerformed
        // TODO add your handling code here:
        Listarentrada le = new Listarentrada();
        le.setVisible(true); 
    }//GEN-LAST:event_jMenuItemEntradasanimalesActionPerformed

    private void jMenuItemResumenVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemResumenVentasActionPerformed
        // TODO add your handling code here:
        ListarVentas list = new ListarVentas();
        list.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemResumenVentasActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        EstadisticaGeneral list = new EstadisticaGeneral();
        list.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        AnimalesSubastado ans = new AnimalesSubastado();
        ans.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
        Resumendecompra rc = new Resumendecompra();
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        RptCuentasxPagar sw = new RptCuentasxPagar();
        sw.setVisible(true);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BP01;
    public static javax.swing.JButton BP02;
    public static javax.swing.JButton BP03;
    public static javax.swing.JButton BP04;
    public static javax.swing.JButton BP05;
    public static javax.swing.JButton BP06;
    public static javax.swing.JMenuItem MA01;
    public static javax.swing.JMenuItem MA02;
    public static javax.swing.JMenuItem MA03;
    public static javax.swing.JMenu MB01;
    public static javax.swing.JMenuItem MB02;
    public static javax.swing.JMenu MB03;
    public static javax.swing.JMenu MB04;
    public static javax.swing.JMenu MB05;
    public static javax.swing.JMenuItem MB06;
    public static javax.swing.JMenu MC01;
    public static javax.swing.JMenu MR01;
    public static javax.swing.JMenu MR02;
    public static javax.swing.JMenu MR03;
    public static javax.swing.JMenu MR04;
    public static javax.swing.JMenu MR05;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemCuentasbancarias;
    private javax.swing.JMenuItem jMenuItemDepositos;
    private javax.swing.JMenuItem jMenuItemEntradasanimales;
    private javax.swing.JMenuItem jMenuItemListadeusuarios;
    private javax.swing.JMenuItem jMenuItemListarcheques;
    private javax.swing.JMenuItem jMenuItemNotas;
    private javax.swing.JMenuItem jMenuItemProveedores;
    private javax.swing.JMenuItem jMenuItemResumenVentas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    public static javax.swing.JLabel tipo;
    public static javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables

    
}
